image: Visual Studio 2017
version: "{build}"
branches:
  only:
    - master
init:
  - git config --global core.autocrlf true
build: off
before_test:
  - ps: appveyor DownloadFile https://download.microsoft.com/download/D/7/2/D725E47F-A4F1-4285-8935-A91AE2FCC06A/dotnet-sdk-2.0.3-win-gs-x64.exe -FileName "C:\dotnet.exe"
  - cmd: call C:\dotnet.exe /install /quiet /norestart
  - cmd: dotnet --info
  - cmd: dotnet restore tests\XRoadProvider.Tests\XRoadProvider.Tests.fsproj
test_script:
  - cmd: dotnet test tests\XRoadProvider.Tests\XRoadProvider.Tests.fsproj --configuration Debug
